DROP TABLE IF EXISTS `player_base_info`;
CREATE TABLE `player_base_info` (
  `playerid` int(10) NOT NULL,
  `udid` varchar(80) DEFAULT NULL,
  `name` varchar(10) DEFAULT NULL,
  `pvp_medal` varchar(60) DEFAULT '0',
  `gem` varchar(60) DEFAULT '0',
  `revive` varchar(100) DEFAULT '100000',
  `cash` varchar(100) DEFAULT '0',
  `game_level` int(7) DEFAULT '1',
  `game_wave` int(10) DEFAULT '0',
  `chanllenge_date` varchar(10) DEFAULT '',
  `chanllenge_num` int(3) DEFAULT '0',
  `avatorid` int(4) DEFAULT '98',
  `lootequiplevel` int(7) DEFAULT '0',
  `is_brush` int(1) DEFAULT '0',
  `last_cmd_time` varchar(25) DEFAULT '',
  `random_reward_num` int(7) DEFAULT '0',
  `random_reward_date` varchar(25) DEFAULT '',
  `lastTimedRewardDatetime` varchar(25) DEFAULT '2015-05-1 8:00:00',
  `last_timed_reward_ranknum` int(7) DEFAULT '100000',
  `last_challenge_datetime` varchar(25) DEFAULT '2015-05-1 8:00:00',
  `buy_del_challenge_cd_num` bigint(20) DEFAULT '0',
  `daily_datetime` varchar(25) DEFAULT '2015-05-1 8:00:00',
  `add_chanllenge_num` bigint(14) DEFAULT '0',
  `awake_spell_num` int(7) DEFAULT '0',
  `last_free_draw_datetime` varchar(25) DEFAULT '2015-10-1 8:00:00',
  `recharge_total_num` int(7) DEFAULT '0',
  `recharge_get_gifts_status` varchar(25) DEFAULT '0',
  `last_login_date` varchar(25) DEFAULT '2015-10-1 8:00:00',
  `login_num` int(7) DEFAULT '0',
  `login_get_gifts_status` varchar(27) DEFAULT '0',
  `tutorial` varchar(25) DEFAULT '0',
  PRIMARY KEY (`playerid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;